# Generated by Django 2.0 on 2018-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_post',
            name='sensor_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
