# Generated by Django 2.0 on 2018-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sensor_post_sensor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_post',
            name='sensor_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
