# Generated by Django 2.0 on 2018-09-07 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fund',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('fname', models.CharField(blank=True, max_length=14, null=True)),
                ('lname', models.CharField(blank=True, max_length=14, null=True)),
                ('dob', models.DateField(blank=True, max_length=14, null=True)),
                ('city', models.CharField(blank=True, max_length=14, null=True)),
                ('address', models.CharField(blank=True, max_length=14, null=True)),
                ('t_address', models.CharField(blank=True, max_length=50, null=True)),
                ('products', models.CharField(blank=True, max_length=14, null=True)),
                ('business_date', models.DateField(blank=True, max_length=14, null=True)),
                ('business_worth', models.CharField(blank=True, default=111111111, max_length=14, null=True)),
                ('have_kids', models.BooleanField()),
                ('num_kids', models.IntegerField(blank=True, null=True)),
                ('with_spouse', models.BooleanField()),
                ('why_no_spouse', models.CharField(blank=True, max_length=20, null=True)),
                ('business_needs', models.CharField(blank=True, max_length=14, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=20, null=True)),
                ('change_business', models.BooleanField()),
                ('fund_needed', models.IntegerField(blank=True, null=True)),
                ('do_you_save', models.BooleanField()),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('cell_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, default=' ', max_length=256, null=True)),
                ('phone', models.CharField(blank=True, default=0, max_length=14, null=True)),
                ('fname', models.CharField(blank=True, default=' ', max_length=14, null=True)),
                ('lname', models.CharField(blank=True, default=' ', max_length=14, null=True)),
                ('dob', models.DateField(blank=True, default='', max_length=14, null=True)),
                ('superuser', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='funds',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.Trader'),
        ),
    ]
