# Generated by Django 2.0 on 2018-09-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='t_address',
            new_name='trade_address',
        ),
    ]
