# Generated by Django 2.0 on 2018-09-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_auto_20180907_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cell',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='business_worth',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
    ]
