# Generated by Django 2.0 on 2018-09-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0005_auto_20180907_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='added',
            field=models.DateField(auto_now=True),
        ),
    ]
