# Generated by Django 2.0 on 2018-09-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_trader_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='superuser',
        ),
    ]
